[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
database = { workspace = true }
axum = { workspace = true }
tower-sessions = { workspace = true }
serde = { workspace = true }
clap = { workspace = true }
sqlx = { workspace = true }
